name: new

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ShellCheck latest release
        id: shellcheck
        run: |
          _release=$(
            curl \
              --fail \
              --silent \
              --location \
              --show-error \
              https://api.github.com/repos/koalaman/shellcheck/releases/latest \
              | jq \
                --raw-output \
                '.tag_name'
          )

          printf '{release}={%s}\n' "$_release" >> "$GITHUB_OUTPUT"

      - name: ShellCheck binaries latest release
        id: shellcheck_binaries
        run: |
          _release=$(
            curl \
              --fail \
              --silent \
              --location \
              --show-error \
              https://api.github.com/repos/vscode-shellcheck/shellcheck-binaries/releases/latest \
              | jq \
                --raw-output \
                '.tag_name'
          )

          printf '{release}={%s}\n' "$_release" >> "$GITHUB_OUTPUT"

      - name: Shellcheck homebrew container image exist
        id: shellcheck_homebrew
        run: |
          _release_exist=$(
            curl \
              --fail \
              --silent \
              --location \
              --show-error \
              --header "Authorization: Bearer $(printf '%s\n' "${{ secrets.GITHUB_TOKEN }}" | base64)" \
              https://ghcr.io/v2/homebrew/core/shellcheck/tags/list \
              | jq \
                --raw-output \
                --arg release "$(printf '%s\n' "${{ steps.shellcheck.outputs.release }}" | sed 's/^.\{1\}//')" \
                'any(.tags[]; . == $release)'
          )

          printf '{release_exist}={%s}\n' "$_release_exist" >> "$GITHUB_OUTPUT"

      - name: Tag ${{ steps.shellcheck.outputs.release }}
        uses: rickstaa/action-create-tag@v1
        if: (steps.shellcheck.outputs.release != steps.shellcheck_binaries.outputs.release) && steps.shellcheck_homebrew.outputs.release_exist == 'true'
        with:
          tag: ${{ steps.shellcheck.outputs.release }}
